version: '3'
services:
  neo4j:
    image: neo4j
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - /home/openrtm/neo4j/data:/data
    networks:
      - webnet
    environment:
      - NEO4J_AUTH=neo4j/rrp
  web:
    image: florisjuh/rrp-vpe:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - 3000:3000
    networks:
      - webnet
    depends_on:
      - 'neo4j'
networks:
  webnet:
